#pragma once

// Generate on Thu Mar 06 18:31:30 2025

/*</> These sdk were generated by the MONSTER tool
contact: @EspSAFE </>*/

namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// ScriptStruct NiagaraCore.NiagaraCompileHash
// 0x000C
struct FNiagaraCompileHash
{
	TArray<unsigned char>                              DataHash;                                                 // 0x0000(0x000C) (ZeroConstructor)
};

}

