#pragma once

// Generate on Thu Mar 06 18:31:30 2025

/*</> These sdk were generated by the MONSTER tool
contact: @EspSAFE </>*/

namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// Class UgcLua.CreativeLuaVM
// 0x019C (0x01B8 - 0x001C)
class UCreativeLuaVM : public UObject
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x001C(0x0004) MISSED OFFSET
	uint64_t                                           SuspendFrameCounter;                                      // 0x0020(0x0008) (Edit, ZeroConstructor, IsPlainOldData)
	uint64_t                                           RunFrameCounter;                                          // 0x0028(0x0008) (Edit, ZeroConstructor, IsPlainOldData)
	int                                                CostCheckInterval;                                        // 0x0030(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x4];                                       // 0x0034(0x0004) MISSED OFFSET
	double                                             FrameExecuteTime;                                         // 0x0038(0x0008) (Edit, ZeroConstructor, IsPlainOldData)
	double                                             SuspendFrameExecuteTime;                                  // 0x0040(0x0008) (Edit, ZeroConstructor, IsPlainOldData)
	int                                                CrossVMAPICost;                                           // 0x0048(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	class UWorld*                                      World;                                                    // 0x004C(0x0004) (ZeroConstructor, IsPlainOldData)
	class AWorldSettings*                              WorldSettings;                                            // 0x0050(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0xC];                                       // 0x0054(0x000C) MISSED OFFSET
	bool                                               bExitWhenFatalOccurs;                                     // 0x0060(0x0001) (BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	bool                                               bExecuting;                                               // 0x0061(0x0001) (BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	bool                                               bAbort;                                                   // 0x0062(0x0001) (BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               bCanFreeze;                                               // 0x0063(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0x4];                                       // 0x0064(0x0004) MISSED OFFSET
	struct FScriptDelegate                             AtPanicDelegate;                                          // 0x0068(0x0010) (ZeroConstructor, InstancedReference)
	unsigned char                                      UnknownData04[0x10];                                      // 0x0078(0x0010) MISSED OFFSET
	struct FScriptDelegate                             CodeFinishDelegate;                                       // 0x0088(0x0010) (ZeroConstructor, InstancedReference)
	struct FScriptDelegate                             CodeOutputDelegate;                                       // 0x0098(0x0010) (ZeroConstructor, InstancedReference)
	struct FScriptDelegate                             HasEventToRunDelegate;                                    // 0x00A8(0x0010) (ZeroConstructor, InstancedReference)
	struct FScriptDelegate                             PrepareEventDelegate;                                     // 0x00B8(0x0010) (ZeroConstructor, InstancedReference)
	struct FScriptDelegate                             ExecuteDelayedDelegate;                                   // 0x00C8(0x0010) (ZeroConstructor, InstancedReference)
	unsigned char                                      UnknownData05[0x14];                                      // 0x00D8(0x0014) MISSED OFFSET
	struct FString                                     MainModule;                                               // 0x00EC(0x000C) (ZeroConstructor)
	struct FString                                     EventHandlerName;                                         // 0x00F8(0x000C) (ZeroConstructor)
	TScriptInterface<class UCreativeEntityInterface>   EntityInterface;                                          // 0x0104(0x0008) (BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData06[0xAC];                                      // 0x010C(0x00AC) MISSED OFFSET

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class UgcLua.CreativeLuaVM");
		return pStaticClass;
	}


	void Step();
	void SetNowRC(int idx);
	void SetCodeOutputDelegate(const struct FScriptDelegate& InDelegate);
	void SetCodeFinishDelegate(const struct FScriptDelegate& InDelegate);
	void Reset();
	void RequireMain();
	void RegisterLuaFunctions(const struct FString& ModuleName, TArray<struct FString> OpenFunctions);
	void RegisterLuaAPIStringValue(const struct FString& ModuleName, const struct FString& Name, const struct FString& Value);
	void RegisterLuaAPINumberValue(const struct FString& ModuleName, const struct FString& Name, float Value);
	void RegisterLuaAPIBoolValue(const struct FString& ModuleName, const struct FString& Name, bool Value);
	void RefreshLastCommentInfo();
	void PostInit();
	void KillJob(int JobId);
	void Init(int MemLimit);
	int GetNowRC();
	struct FString GetLastCommentInfo();
	void FreezeGameTime(bool bCond);
	void ExtractCurrentCode(int* CodeIdx, struct FString* code);
	int EnqueueCode(struct FString* RuntimeCode, int* CodeUID);
	struct FString DescribeLuaThread();
	void Close();
	void AllowRequire(bool bAllow);
};


// Class UgcLua.CreativeEntityInterface
// 0x0000 (0x0020 - 0x0020)
class UCreativeEntityInterface : public UInterface
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class UgcLua.CreativeEntityInterface");
		return pStaticClass;
	}


	class UObject* UUID2UObject(int64_t* UUID);
	bool UUID2Type(int64_t* UUID, EEntityType* Type, unsigned char* SubType);
	uint32_t UUID2Key(int64_t* UUID);
	void RemoveUUID(int64_t* UUID);
	int64_t GetInstanceObjectUUID(int64_t* UUID);
	int64_t CreateEntityIfNotExistsFromUObject(class UObject* Object, EEntityType* Type, unsigned char* SubType);
	int64_t CreateEntityIfNotExistsFromKey(uint32_t* Key, EEntityType* Type, unsigned char* SubType);
};


}

